# Generated by Django 4.2.20 on 2025-11-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en USD')),
                ('tasa_cambio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tasa de Cambio')),
                ('monto_pesos', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monto en DOP')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Conversión')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='convertidor/', verbose_name='Imagen de Factura')),
            ],
            options={
                'verbose_name': 'Movimiento de Entrada',
                'verbose_name_plural': 'Movimientos de Entrada',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ServicioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('LUZ', 'Electricidad'), ('AGUA', 'Agua'), ('INTERNET', 'Internet'), ('TELEFONO', 'Teléfono'), ('ALQUILER', 'Alquiler'), ('OTRO', 'Otro Servicio')], max_length=20, verbose_name='Tipo de Servicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Pago')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del Pago')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pago')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EDITADO', 'Editado'), ('ELIMINADO', 'Eliminado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='ACTIVO', max_length=20, verbose_name='Estado del Pago')),
                ('tipo_comprobante', models.CharField(choices=[('SIN_COMPROBANTE', 'Sin Comprobante'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo'), ('TICKET', 'Ticket'), ('TRANSFERENCIA', 'Transferencia')], default='SIN_COMPROBANTE', max_length=20, verbose_name='Tipo de Comprobante')),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Comprobante')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor del Servicio')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen de Comprobante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.movimientoentrada', verbose_name='Movimiento Asociado')),
            ],
            options={
                'verbose_name': 'Pago de Servicio',
                'verbose_name_plural': 'Pagos de Servicios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ALIMENTACION', 'Alimentación'), ('TRANSPORTE', 'Transporte'), ('COMPRAS', 'Compras'), ('SALUD', 'Salud'), ('PERSONAL', 'Gastos Personales'), ('OTROS', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Gasto')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del Gasto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Gasto')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EDITADO', 'Editado'), ('ELIMINADO', 'Eliminado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='ACTIVO', max_length=20, verbose_name='Estado del Gasto')),
                ('tipo_comprobante', models.CharField(choices=[('SIN_COMPROBANTE', 'Sin Comprobante'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo'), ('TICKET', 'Ticket'), ('TRANSFERENCIA', 'Transferencia')], default='SIN_COMPROBANTE', max_length=20, verbose_name='Tipo de Comprobante')),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Comprobante')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='gastos/', verbose_name='Imagen de Comprobante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.movimientoentrada', verbose_name='Movimiento Asociado')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
    ]
