# Generated by Django 4.2.20 on 2025-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_movimientoentrada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoentrada',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de Conversión'),
        ),
    ]
