# Generated by Django 4.2.20 on 2025-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_movimientoentrada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha del Gasto'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha del Pago'),
        ),
    ]
