# Generated by Django 4.2.20 on 2025-12-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_gasto_fecha_alter_gasto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_actualizacion',
            field=models.DateTimeField(verbose_name='Fecha de Actualización'),
        ),
    ]
