# Generated by Django 4.2.20 on 2025-12-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_gasto_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
