# Generated by Django 4.2.20 on 2025-12-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_gasto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
