# Generated by Django 4.2.20 on 2026-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_gasto_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_comprobante',
            field=models.CharField(choices=[('SIN_COMPROBANTE', 'Sin Comprobante'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo'), ('TICKET', 'Ticket'), ('TRANSFERENCIA', 'Transferencia'), ('RAFAEL', 'Rafael')], default='SIN_COMPROBANTE', max_length=20, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='tipo_comprobante',
            field=models.CharField(choices=[('SIN_COMPROBANTE', 'Sin Comprobante'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo'), ('TICKET', 'Ticket'), ('TRANSFERENCIA', 'Transferencia'), ('RAFAEL', 'Rafael')], default='SIN_COMPROBANTE', max_length=20, verbose_name='Tipo de Comprobante'),
        ),
    ]
