# Generated by Django 4.2.20 on 2026-03-20 17:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import finanzas.models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_alter_gasto_tipo_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='movimientoentrada',
            options={'verbose_name': 'Movimiento de Entrada', 'verbose_name_plural': 'Movimientos de Entrada'},
        ),
        migrations.AlterModelOptions(
            name='serviciopago',
            options={'verbose_name': 'Pago de Servicio', 'verbose_name_plural': 'Pagos de Servicios'},
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.movimientoentrada', verbose_name='Movimiento Asociado'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EDITADO', 'Editado'), ('ELIMINADO', 'Eliminado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=finanzas.models.upload_gastos, validators=[finanzas.models.validar_imagen], verbose_name='Imagen de Comprobante'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='notas',
            field=models.TextField(blank=True, default='', verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='numero_comprobante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de Comprobante'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='movimientoentrada',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='movimientoentrada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=finanzas.models.upload_convertidor, validators=[finanzas.models.validar_imagen], verbose_name='Imagen de Factura'),
        ),
        migrations.AlterField(
            model_name='movimientoentrada',
            name='monto_pesos',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Monto en DOP'),
        ),
        migrations.AlterField(
            model_name='movimientoentrada',
            name='monto_usd',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto en USD'),
        ),
        migrations.AlterField(
            model_name='movimientoentrada',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tasa de Cambio'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.movimientoentrada', verbose_name='Movimiento Asociado'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EDITADO', 'Editado'), ('ELIMINADO', 'Eliminado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=finanzas.models.upload_servicios, validators=[finanzas.models.validar_imagen], verbose_name='Imagen de Comprobante'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='notas',
            field=models.TextField(blank=True, default='', verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='numero_comprobante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de Comprobante'),
        ),
        migrations.AlterField(
            model_name='serviciopago',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['-fecha'], name='idx_gasto_fecha'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['estado'], name='idx_gasto_estado'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['entrada', 'estado'], name='idx_gasto_entrada_estado'),
        ),
        migrations.AddIndex(
            model_name='movimientoentrada',
            index=models.Index(fields=['-fecha'], name='idx_entrada_fecha'),
        ),
        migrations.AddIndex(
            model_name='serviciopago',
            index=models.Index(fields=['-fecha'], name='idx_servicio_fecha'),
        ),
        migrations.AddIndex(
            model_name='serviciopago',
            index=models.Index(fields=['estado'], name='idx_servicio_estado'),
        ),
        migrations.AddIndex(
            model_name='serviciopago',
            index=models.Index(fields=['entrada', 'estado'], name='idx_servicio_entrada_estado'),
        ),
        migrations.AddConstraint(
            model_name='gasto',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='gasto_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='serviciopago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='servicio_monto_positivo'),
        ),
    ]
