# Generated by Django 4.2.20 on 2026-03-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0009_alter_gasto_options_alter_movimientoentrada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoentrada',
            name='monto_pesos',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automáticamente (monto_usd × tasa_cambio). Usar siempre .save() — nunca QuerySet.update().', max_digits=14, verbose_name='Monto en DOP'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID de Solicitud')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Sesión')),
                ('ruta', models.CharField(blank=True, max_length=255, verbose_name='Ruta HTTP')),
                ('metodo_http', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('modulo', models.CharField(choices=[('SEGURIDAD', 'Seguridad'), ('VENTAS', 'Ventas'), ('ANULACIONES', 'Anulaciones'), ('DEVOLUCIONES', 'Devoluciones'), ('COBROS', 'Cobros'), ('PRECIOS', 'Precios'), ('INVENTARIO', 'Inventario'), ('USUARIOS', 'Usuarios'), ('SISTEMA', 'Sistema'), ('FINANZAS', 'Finanzas')], max_length=20, verbose_name='Módulo')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FALLIDO', 'Login fallido'), ('ANULAR', 'Anular'), ('DEVOLUCION', 'Devolución'), ('PAGO', 'Pago'), ('CAMBIO_PRECIO', 'Cambio precio'), ('CAMBIO_INVENTARIO', 'Cambio inventario'), ('CAMBIO_PASSWORD', 'Cambio password'), ('CAMBIO_PERMISOS', 'Cambio permisos')], max_length=30, verbose_name='Acción')),
                ('canal', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('CRON', 'Cron'), ('SHELL', 'Shell')], default='WEB', max_length=10, verbose_name='Canal')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo Django')),
                ('tabla_bd', models.CharField(blank=True, max_length=100, verbose_name='Tabla en BD')),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID del Objeto')),
                ('objeto_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Objeto')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('data_detalle', models.JSONField(blank=True, null=True, verbose_name='Detalle JSON')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP del Cliente')),
                ('ip_proxy', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Proxy')),
                ('navegador', models.CharField(blank=True, max_length=255, verbose_name='Navegador')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('dispositivo', models.CharField(blank=True, max_length=255, verbose_name='Dispositivo')),
                ('os', models.CharField(blank=True, max_length=255, verbose_name='Sistema Operativo')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='Nivel')),
                ('riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=10, verbose_name='Riesgo')),
                ('firma', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Firma de Integridad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['modulo', 'timestamp'], name='idx_audit_modulo_ts'), models.Index(fields=['user', 'modulo'], name='idx_audit_user_modulo'), models.Index(fields=['accion'], name='idx_audit_accion'), models.Index(fields=['request_id'], name='idx_audit_request'), models.Index(fields=['ip_address'], name='idx_audit_ip'), models.Index(fields=['objeto_id'], name='idx_audit_objeto'), models.Index(fields=['nivel', 'timestamp'], name='idx_audit_nivel_ts')],
            },
        ),
    ]
