# Generated by Django 4.2.20 on 2026-03-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_alter_movimientoentrada_monto_pesos_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(default='USD', max_length=3)),
                ('target', models.CharField(default='DOP', max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base', 'target', 'date'], name='finanzas_ex_base_18b8ab_idx')],
                'unique_together': {('base', 'target', 'date')},
            },
        ),
    ]
