"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # ← TRES .parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-6amk(11q7n4-e3y13k!vb0@$6lo@5me-+bnjmofia&2zwf%9v%'
SECRET_KEY = os.environ.get('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv("DEBUG", "False") == "True"
# ALLOWED_HOSTS = []
# settings.py

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'omega-neighbourless-sublabially.ngrok-free.dev', 'mcl-finanza-1.onrender.com', ' codearicos.pythonanywhere.com ']
# ALLOWED_HOSTS = ['*']

# CSRF_TRUSTED_ORIGINS = [
    # 'https://*.ngrok-free.dev',  # Para permitir cualquier subdominio de ngrok-free.dev
    # 'https://omega-neighbourless-sublabially.ngrok-free.dev' # La URL específica
# ]
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8003', 'http://localhost:8003']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'finanzas.apps.FinanzasConfig',
    'finanzas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
     # 'django.middleware.cache.FetchFromCacheMiddleware',
#    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',
    
    
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "TEMPLATES"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", # esto es para mysql
            # 'sslmode': 'require',
            # 'options': '-c default_transaction_read_only=off'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_TZ = True


# Configuración de zona horaria para República Dominicana
# TIME_ZONE = 'America/Santo_Domingo'
# USE_TZ = True

# Idioma por defecto
LANGUAGE_CODE = 'en-us'
USE_L10N = False

# Formato de fecha
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i:s'


# LOGIN_URL = '/login/'  # Instead of the default '/accounts/login/'
LOGIN_REDIRECT_URL = '/convertidor/' # Where to redirect after login
LOGOUT_REDIRECT_URL = '/'  # Where to redirect after logout

# Tiempo de vida de la sesión en segundos (10 minutos)
SESSION_COOKIE_AGE = 3600

# Refresca la sesión en cada petición (mantiene al usuario activo si navega)
SESSION_SAVE_EVERY_REQUEST = True

# La sesión expira al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# URL a la que redirigir si se requiere login (usa el 'name' de tu URL de login)
LOGIN_URL = 'index'

CSRF_COOKIE_SECURE = False  # Cambiar a True en producción con HTTPS
CSRF_USE_SESSIONS = False
# Elimina la sesión de la base de datos al cerrar
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Forzar a que la cookie expire de inmediato al cerrar el navegador
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# No permitir que la sesión se use en múltiples pestañas si una ya cerró
SESSION_COOKIE_HTTPONLY = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Directorio donde Django almacenará los arachivos subidos (ej. comprobantes)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# CONFIGURACION PARA LOS LOGS DE DJANGO
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,

#     'formatters': {
#         'standard': {
#             'format': '[{levelname}] {asctime} {name}: {message}',
#             'style': '{',
#         }
#     },

#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'standard',
#         },
#     },

#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'INFO',
#         },
#         'django.request': {
#             'handlers': ['console'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#         'derej_clan': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     }
# }
import os

# DEBUG = os.getenv("DEBUG", "False") == "True"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
