# Generated by Django 4.2.20 on 2026-05-01 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icono', models.CharField(max_length=60)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legible', models.CharField(help_text="Texto visible al usuario: 'Aplicar descuento'", max_length=100)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='seguridad.modulo')),
                ('permiso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modulo_info', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Permiso de módulo',
                'verbose_name_plural': 'Permisos de módulos',
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_acceso', models.BooleanField(default=True, help_text='True = concede extra | False = bloquea del rol')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_creados', to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override de permiso',
                'verbose_name_plural': 'Overrides de permisos',
                'unique_together': {('usuario', 'permiso')},
            },
        ),
    ]
