# Generated by Django 4.2.20 on 2026-05-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='url_name',
            field=models.CharField(blank=True, help_text='Nombre de la ruta (URL name)', max_length=100, null=True),
        ),
    ]
