# Generated by Django 4.2.20 on 2026-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_modulo_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='url_name',
            field=models.CharField(blank=True, choices=[('dashboard', 'Dashboard Financiero'), ('convertidor', 'Conversor de Divisas'), ('gastos', 'Gestión de Gastos'), ('servicios', 'Pago de Servicios'), ('roles-index', 'Seguridad y Roles')], help_text='Seleccione la vista a la que apunta este módulo', max_length=100, null=True),
        ),
    ]
