# Generated by Django 4.2.20 on 2026-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_alter_modulo_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='icono',
            field=models.CharField(choices=[('fas fa-chart-line', 'Línea de Gráfico (Dashboard)'), ('fas fa-exchange-alt', 'Flechas de Cambio (Conversiones)'), ('fas fa-wallet', 'Billetera (Gastos)'), ('fas fa-file-invoice-dollar', 'Factura (Servicios)'), ('fas fa-shield-halved', 'Escudo (Seguridad)'), ('fas fa-home', 'Casa (Inicio)'), ('bx bxs-dashboard', 'Box Dashboard'), ('bx bxs-user-badge', 'Box Usuario'), ('bx bxs-lock-alt', 'Box Candado'), ('bx bxs-file-find', 'Box Auditoría')], default='fas fa-folder', help_text='Seleccione el icono visual del módulo', max_length=60),
        ),
    ]
